use crate::component_info::{CONTROL_BUMP_SCORES1, CONTROL_BUMP_SCORES2, ComponentInfo};
use crate::control::{ComponentControl, ComponentControlCallback};
use crate::control_function::{
    bumper_control, left_kicker_gate_control, right_kicker_gate_control,
};
use crate::state::component_state::ComponentState;
use crate::t_pinball_table::TPinballTable;
use std::cell::RefCell;
use std::rc::{Rc, Weak};

pub const CHEAT_LEN: usize = 11;

pub struct ControlState {
    pub table_g: Option<Weak<RefCell<TPinballTable>>>,
    pub score_components: Vec<ComponentInfo>,
    pub simple_components: Vec<ComponentInfo>,
    pub easy_mode: bool,
    pub table_unlimited_balls: bool,
    pub cheat_buffer: RefCell<[u8; CHEAT_LEN]>,
    pub component_state: ComponentState,
}

fn info(
    name: &'static str,
    control_func: ComponentControlCallback,
    score_count: u32,
    scores: &[i32],
) -> ComponentInfo {
    ComponentInfo {
        name,
        control: Rc::new(RefCell::new(ComponentControl {
            control_func,
            score_count,
            scores: scores.to_vec(),
        })),
    }
}

impl ControlState {
    pub fn new() -> ControlState {
        Self {
            table_g: None,
            score_components: Self::init_score_components(),
            simple_components: Self::init_simple_components(),
            easy_mode: false,
            table_unlimited_balls: false,
            cheat_buffer: RefCell::new([0; CHEAT_LEN]),
            component_state: ComponentState::default(),
        }
    }

    fn init_score_components() -> Vec<ComponentInfo> {
        // TODO: Add score components as their concrete component types and
        // control callbacks are ported.
        vec![
            info("a_bump1", bumper_control, 4, &CONTROL_BUMP_SCORES1),
            info("a_bump2", bumper_control, 4, &CONTROL_BUMP_SCORES1),
            info("a_bump3", bumper_control, 4, &CONTROL_BUMP_SCORES1),
            info("a_bump4", bumper_control, 4, &CONTROL_BUMP_SCORES1),
            info("a_bump5", bumper_control, 4, &CONTROL_BUMP_SCORES2),
            info("a_bump6", bumper_control, 4, &CONTROL_BUMP_SCORES2),
            info("a_bump7", bumper_control, 4, &CONTROL_BUMP_SCORES2),
            info("v_gate1", left_kicker_gate_control, 0, &[]),
            info("v_gate2", right_kicker_gate_control, 0, &[]),
        ]
        // component_info{control_roll3_tag, {ReentryLanesRolloverControl, 1, control_roll_scores1}},
        // component_info{control_roll2_tag, {ReentryLanesRolloverControl, 1, control_roll_scores1}},
        // component_info{control_roll1_tag, {ReentryLanesRolloverControl, 1, control_roll_scores1}},
        // component_info{control_attack_bump_tag, {BumperGroupControl, 0, nullptr}},
        // component_info{control_bump5_tag, {BumperControl, 4, control_bump_scores2}},
        // component_info{control_bump6_tag, {BumperControl, 4, control_bump_scores2}},
        // component_info{control_bump7_tag, {BumperControl, 4, control_bump_scores2}},
        // component_info{control_roll112_tag, {LaunchLanesRolloverControl, 1, control_roll_scores2}},
        // component_info{control_roll111_tag, {LaunchLanesRolloverControl, 1, control_roll_scores2}},
        // component_info{control_roll110_tag, {LaunchLanesRolloverControl, 1, control_roll_scores2}},
        // component_info{control_launch_bump_tag, {BumperGroupControl, 0, nullptr}},
        // component_info{control_rebo1_tag, {FlipperRebounderControl1, 1, control_rebo_score1}},
        // component_info{control_rebo2_tag, {FlipperRebounderControl2, 1, control_rebo_score1}},
        // component_info{control_rebo3_tag, {RebounderControl, 1, control_rebo_score1}},
        // component_info{control_rebo4_tag, {RebounderControl, 1, control_rebo_score1}},
        // component_info{control_kicker1_tag, {LeftKickerControl, 0, nullptr}},
        // component_info{control_kicker2_tag, {RightKickerControl, 0, nullptr}},
        // component_info{control_gate1_tag, {LeftKickerGateControl, 0, nullptr}},
        // component_info{control_gate2_tag, {RightKickerGateControl, 0, nullptr}},
        // component_info{control_oneway4_tag, {DeploymentChuteToEscapeChuteOneWayControl, 6, control_oneway4_score1}},
        // component_info{control_oneway10_tag, {DeploymentChuteToTableOneWayControl, 0, nullptr}},
        // component_info{control_block1_tag, {DrainBallBlockerControl, 0, nullptr}},
        // component_info{control_ramp_tag, {LaunchRampControl, 1, control_ramp_score1}},
        // component_info{control_ramp_hole_tag, {LaunchRampHoleControl, 0, nullptr}},
        // component_info{control_roll4_tag, {OutLaneRolloverControl, 1, control_roll_score1}},
        // component_info{control_roll8_tag, {OutLaneRolloverControl, 1, control_roll_score1}},
        // component_info{control_lite17_tag, {ExtraBallLightControl, 0, nullptr}},
        // component_info{control_roll6_tag, {ReturnLaneRolloverControl, 2, control_roll_score2}},
        // component_info{control_roll7_tag, {ReturnLaneRolloverControl, 2, control_roll_score2}},
        // component_info{control_roll5_tag, {BonusLaneRolloverControl, 1, control_roll_score3}},
        // component_info{control_roll179_tag, {FuelRollover1Control, 1, control_roll_score4}},
        // component_info{control_roll180_tag, {FuelRollover2Control, 1, control_roll_score4}},
        // component_info{control_roll181_tag, {FuelRollover3Control, 1, control_roll_score4}},
        // component_info{control_roll182_tag, {FuelRollover4Control, 1, control_roll_score4}},
        // component_info{control_roll183_tag, {FuelRollover5Control, 1, control_roll_score4}},
        // component_info{control_roll184_tag, {FuelRollover6Control, 1, control_roll_score4}},
        // component_info{control_flag1_tag, {FlagControl, 2, control_flag_score1}},
        // component_info{control_kickout2_tag, {HyperspaceKickOutControl, 5, control_kickout_score1}},
        // component_info{control_hyper_lights_tag, {HyperspaceLightGroupControl, 0, nullptr}},
        // component_info{control_flag2_tag, {FlagControl, 2, control_flag_score1}},
        // component_info{control_sink1_tag, {WormHoleControl, 3, control_sink_score1}},
        // component_info{control_sink2_tag, {WormHoleControl, 3, control_sink_score1}},
        // component_info{controlsink3_tag, {WormHoleControl, 3, control_sink_score1}},
        // component_info{control_flip1_tag, {LeftFlipperControl, 0, nullptr}},
        // component_info{control_flip2_tag, {RightFlipperControl, 0, nullptr}},
        // component_info{control_plunger_tag, {PlungerControl, 0, nullptr}},
        // component_info{control_target1_tag, {BoosterTargetControl, 2, control_target_score1}},
        // component_info{control_target2_tag, {BoosterTargetControl, 2, control_target_score1}},
        // component_info{control_target3_tag, {BoosterTargetControl, 2, control_target_score1}},
        // component_info{control_lite60_tag, {JackpotLightControl, 0, nullptr}},
        // component_info{control_lite59_tag, {BonusLightControl, 0, nullptr}},
        // component_info{control__target6_tag, {MedalTargetControl, 3, control_target_score2}},
        // component_info{control_target5_tag, {MedalTargetControl, 3, control_target_score2}},
        // component_info{control_target4_tag, {MedalTargetControl, 3, control_target_score2}},
        // component_info{control_bumber_target_lights_tag, {MedalLightGroupControl, 0, nullptr}},
        // component_info{control_target9_tag, {MultiplierTargetControl, 2, control_target_score3}},
        // component_info{control_target8_tag, {MultiplierTargetControl, 2, control_target_score3}},
        // component_info{control_target7_tag, {MultiplierTargetControl, 2, control_target_score3}},
        // component_info{control_top_target_lights_tag, {MultiplierLightGroupControl, 0, nullptr}},
        // component_info{control_target10_tag, {FuelSpotTargetControl, 1, control_target_score4}},
        // component_info{control_target11_tag, {FuelSpotTargetControl, 1, control_target_score4}},
        // component_info{control_target12_tag, {FuelSpotTargetControl, 1, control_target_score4}},
        // component_info{control_target13_tag, {MissionSpotTargetControl, 1, control_target_score5}},
        // component_info{control_target14_tag, {MissionSpotTargetControl, 1, control_target_score5}},
        // component_info{control_target15_tag, {MissionSpotTargetControl, 1, control_target_score5}},
        // component_info{control_target16_tag, {LeftHazardSpotTargetControl, 1, control_target_score6}},
        // component_info{control_target17_tag, {LeftHazardSpotTargetControl, 1, control_target_score6}},
        // component_info{control_target18_tag, {LeftHazardSpotTargetControl, 1, control_target_score6}},
        // component_info{control_target19_tag, {RightHazardSpotTargetControl, 1, control_target_score6}},
        // component_info{control_target20_tag, {RightHazardSpotTargetControl, 1, control_target_score6}},
        // component_info{control_target21_tag, {RightHazardSpotTargetControl, 1, control_target_score6}},
        // component_info{control_target22_tag, {WormHoleDestinationControl, 1, control_target_score7}},
        // component_info{control_roll9_tag, {SpaceWarpRolloverControl, 1, control_roll_score5}},
        // component_info{control_kickout3_tag, {BlackHoleKickoutControl, 1, control_kickout_score2}},
        // component_info{control_kickout1_tag, {GravityWellKickoutControl, 1, control_kickout_score3}},
        // component_info{control_drain_tag, {BallDrainControl, 0, nullptr}},
        // component_info{control_oneway1_tag, {SkillShotGate1Control, 0, nullptr}},
        // component_info{control_trip1_tag, {SkillShotGate2Control, 0, nullptr}},
        // component_info{control_trip2_tag, {SkillShotGate3Control, 0, nullptr}},
        // component_info{control_trip3_tag, {SkillShotGate4Control, 0, nullptr}},
        // component_info{control_trip4_tag, {SkillShotGate5Control, 0, nullptr}},
        // component_info{control_trip5_tag, {SkillShotGate6Control, 0, nullptr}},
        // component_info{control_lite200_tag, {ShootAgainLightControl, 0, nullptr}},
        // component_info{control_sink7_tag, {EscapeChuteSinkControl, 0, nullptr}},
    }

    fn init_simple_components() -> Vec<ComponentInfo> {
        vec![]
        //     &control_lite8_tag,
        // &control_lite9_tag,
        // &control_lite10_tag,
        // &control_bmpr_inc_lights_tag,
        // &control_lite171_tag,
        // &control_lite170_tag,
        // &control_lite169_tag,
        // &control_ramp_bmpr_inc_lights_tag,
        // &control_lite30_tag,
        // &control_lite29_tag,
        // &control_lite1_tag,
        // &control_lite54_tag,
        // &control_lite55_tag,
        // &control_lite56_tag,
        // &control_lite18_tag,
        // &control_lite27_tag,
        // &control_lite28_tag,
        // &control_lite16_tag,
        // &control_lite21_tag,
        // &control_lite22_tag,
        // &control_lite23_tag,
        // &control_lite24_tag,
        // &control_lite25_tag,
        // &control_lite26_tag,
        // &control_lite130_tag,
        // &control_lite5_tag,
        // &control_lite6_tag,
        // &control_lite7_tag,
        // &control_worm_hole_lights_tag,
        // &control_lite4_tag,
        // &control_lite2_tag,
        // &control_lite3_tag,
        // &control_bsink_arrow_lights_tag,
        // &control_l_trek_lights_tag,
        // &control_r_trek_lights_tag,
        // &control_literoll179_tag,
        // &control_literoll180_tag,
        // &control_literoll181_tag,
        // &control_literoll182_tag,
        // &control_literoll183_tag,
        // &control_literoll184_tag,
        // &control_fuel_bargraph_tag,
        // &control_lite20_tag,
        // &control_lite19_tag,
        // &control_lite61_tag,
        // &control_lite58_tag,
        // &control_lite11_tag,
        // &control_lite12_tag,
        // &control_lite13_tag,
        // &control_lite70_tag,
        // &control_lite71_tag,
        // &control_lite72_tag,
        // &control_top_circle_tgt_lights_tag,
        // &control_lite101_tag,
        // &control_lite102_tag,
        // &control_lite103_tag,
        // &control_ramp_tgt_lights_tag,
        // &control_lite104_tag,
        // &control_lite105_tag,
        // &control_lite106_tag,
        // &control_lite107_tag,
        // &control_lite108_tag,
        // &control_lite109_tag,
        // &control_lchute_tgt_lights_tag,
        // &control_bpr_solotgt_lights_tag,
        // &control_lite110_tag,
        // &control_lite62_tag,
        // &control_lite67_tag,
        // &control_lite68_tag,
        // &control_lite69_tag,
        // &control_lite131_tag,
        // &control_lite132_tag,
        // &control_lite133_tag,
        // &control_skill_shot_lights_tag,
        // &control_lite77_tag,
        // &control_lite198_tag,
        // &control_middle_circle_tag,
        // &control_outer_circle_tag,
        // &control_soundwave9_tag,
        // &control_soundwave10_tag,
        // &control_soundwave21_tag,
        // &control_soundwave23_tag,
        // &control_soundwave24_tag,
        // &control_soundwave30_tag,
        // &control_soundwave28_tag,
        // &control_soundwave50_1_tag,
        // &control_soundwave8_tag,
        // &control_soundwave40_tag,
        // &control_soundwave41_tag,
        // &control_soundwave36_1_tag,
        // &control_soundwave50_2_tag,
        // &control_soundwave35_1_tag,
        // &control_soundwave36_2_tag,
        // &control_soundwave35_2_tag,
        // &control_soundwave38_tag,
        // &control_soundwave39_tag,
        // &control_soundwave44_tag,
        // &control_soundwave45_tag,
        // &control_soundwave46_tag,
        // &control_soundwave47_tag,
        // &control_soundwave48_tag,
        // &control_soundwave52_tag,
        // &control_soundwave14_1_tag,
        // &control_soundwave59_tag,
        // &control_lite199_tag,
        // &control_lite196_tag,
        // &control_lite195_tag,
        // &control_info_text_box_tag,
        // &control_mission_text_box_tag,
        // &control_soundwave27_tag,
        // &control_lite84_tag,
        // &control_lite85_tag,
        // &control_soundwave14_2_tag,
        // &control_soundwave3_tag,
        // &control_soundwave26_tag,
        // &control_soundwave49D_tag,
        // &control_lite300_tag,
        // &control_lite301_tag,
        // &control_lite302_tag,
        // &control_lite303_tag,
        // &control_lite304_tag,
        // &control_lite305_tag,
        // &control_lite306_tag,
        // &control_lite307_tag,
        // &control_lite308_tag,
        // &control_lite309_tag,
        // &control_lite310_tag,
        // &control_lite311_tag,
        // &control_lite312_tag,
        // &control_lite313_tag,
        // &control_lite314_tag,
        // &control_lite315_tag,
        // &control_lite316_tag,
        // &control_lite317_tag,
        // &control_lite318_tag,
        // &control_lite319_tag,
        // &control_lite320_tag,
        // &control_lite321_tag,
        // &control_lite322_tag,
        // &control_goal_lights_tag,
        // &control_soundwave25_tag,
        // &control_soundwave7_tag,
        // &control_lite38_tag,
        // &control_lite39_tag,
        // &control_lite40_tag,
    }
}

impl Default for ControlState {
    fn default() -> Self {
        Self::new()
    }
}
