name: Rust CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  components: rustfmt, clippy

            - name: Install SDL2 dependencies with vcpkg
              env:
                  VCPKG_ROOT: ${{ github.workspace }}\vcpkg
              run: |
                  git clone https://github.com/microsoft/vcpkg.git vcpkg
                  .\vcpkg\bootstrap-vcpkg.bat
                  .\vcpkg\vcpkg install sdl2:x64-windows sdl2-mixer:x64-windows

            - name: Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  workspaces: |
                      . -> target
                  cache-all-crates: true
                  save-if: ${{ github.ref == 'refs/heads/main' }}

            # - name: Clippy lints
            #   run: cargo clippy -- -D warnings

            - name: Build
              run: cargo build --release

            # - name: Run tests
            #   run: cargo test --release

            # - name: Upload artifact
            #   uses: actions/upload-artifact@v4
            #   with:

            #       name: windows-binary
            #       path: target/release/*.exe
